### ISSUE TITLE
Auth Issues

### ISSUE THREAD

**Issue by BloodWolf89** [Xxplosions/twitchtv-oauth#3]
When I get the code, I try to echo out the token and it is blank. I take the code and add it to the urn in browser but everything returns null. I only get the code. No token.

I am building a system on my Localhost but I am trying to run it using my IP because I thought it was an issue with it being "LOCALHOST"

**Comment by farazappy** [comment]
Hello, Probably This Should Be The Fix. I Came Across The Same Problem And This Fixed It For Me!

Add `curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);` Before Calling `curl_exec(ch);`

**Comment by EliasRanz** [comment]
I just tested it again on my server and it looked like I was able to get it to authenticate me with no issue with the same code as is in this class. If you're still having the issue can you provide us with the example code that is causing the issue? I believe this is more of a server configuration issue. See the following [stackoverflow post](http://stackoverflow.com/questions/18971983/curl-requires-curlopt-ssl-verifypeer-false). setting verifypeer to false is problematic because then it's connecting insecurely. If you go to the API all of it is available via https.

**Comment by EliasRanz** [comment]
Doesn't seem like this is an issue with the code, more so an issue with server configuration.
